# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Node.js app to Azure Web App - axomera

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
env:
  VERSION: v0.1

jobs:  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: node-app
      - name: Download from Azure storage
        run: |
          az storage blob download --connection-string ${{ secrets.STORAGEKEY1 }} --container-name deployment-ui/ --file $VERSION
        # --file deployment-ui/$VERSION --name "$AZURE_DB_ZIP_FILE_NAME" --container-name "$AZURE_CONTAINER_NAME"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E564E163A38E4D9F97F1A38B3643A675 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_41D1CC525B9F4E7085502BB8ACA93F79 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E8B37AF5535E473F872C402C30708933 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'axomera'
          # slot-name: 'Production'
          package: .
          
